config/routes.rb
Rails.application.routes.draw do

  root controller: :static, action: :landing

  namespace :static, path: '/' do
    get :home
    get :pricing
    get :about
    get :map
    get :events
    get :culture
    get :sport
    get :contact
    get :writeus

    post :writeus, action: :handle_message

    get :gallery
    get 'gallery_content/:id', action: :gallery_content, as: :gallery_content
  end

  resources :albums do
    delete 'images/:id', action: :remove_image, as: :remove_image
    delete 'images', action: :remove_images, as: :remove_images
  end
end

app/models/album.rb
class Album < ActiveRecord::Base

  ### Attributes
  #
  # image
  # hover_image
  # images
  # name
  # position
  #

  serialize :name, Hash
  serialize :images, Array
  # mount_uploader :image, AlbumImageUploader
  # mount_uploader :hover_image, AlbumImageUploader
  # mount_uploaders :images, ImageUploader

  def localized_name locale=I18n.locale
    name[locale]
  end

  I18n.available_locales.each do |locale|
    define_method "#{locale}_name" do
      name[locale]
    end

    define_method "#{locale}_name=" do |val|
      name[locale] = val
    end
  end

  def image_presigned_post
    @image_presigned_post ||= S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: 201, acl: :public_read)
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :authenticate
  before_action :set_album, only: [:show, :edit, :update, :destroy, :remove_image, :remove_images]

  layout 'management'

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to albums_path }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    attrs = album_params

    if attrs[:images]
      @album.images += attrs.delete(:images)
    end

    respond_to do |format|
      if @album.update(attrs)
        # format.html { redirect_to edit_album_path(@album) }
        format.html { redirect_to albums_path }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end

  def remove_image
    if @album.images.count == 1
      @album.images = []
    else
      @album.images.delete_at(params[:id].to_i)
      @album.images = @album.images
    end

    @album.save
    # redirect_to edit_album_path(@album)
  end

  def remove_images
    @album.images = []
    @album.save
    redirect_to edit_album_path(@album)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:album_id] || params[:id])
    end

    def locale_names
      I18n.available_locales.map do |locale|
        [locale, :name].join('_').to_sym
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      permitted_params = [:position, :image, :image_cache, :hover_image, :hover_image_cache, images: []] + locale_names
      params.require(:album).permit(permitted_params)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['USER_ID'] && password == ENV['PASSWORD']
    end
  end

  private

  def set_locale
    if language_change_necessary?
      I18n.locale = the_new_locale
      set_locale_cookie(I18n.locale)
    else
      use_locale_from_cookie
    end
  end

  def language_change_necessary?
    return cookies['locale'].nil? || params[:locale]
  end

  def the_new_locale
    new_locale = (params[:locale] || extract_locale_from_accept_language_header)
    I18n.available_locales.include?(new_locale.to_sym) ? new_locale : I18n.default_locale.to_s
  end

  # Sets the locale cookie
  def set_locale_cookie(locale)
    cookies['locale'] = locale.to_s
  end

  # Reads the locale cookie and sets the locale from it
  def use_locale_from_cookie
    I18n.locale = cookies['locale']
  end

  # Extracts the locale from the accept language header, if found
  def extract_locale_from_accept_language_header
    locale = request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first rescue I18n.default_locale
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  layout 'application'

  def landing
    render layout: false
  end

  def home
    render render_name
  end

  def pricing
  end

  def about
    render render_name
  end

  def map
    render render_name
  end

  def events
    # render render_name
  end

  def culture
    # render render_name
  end

  def sport
    # render render_name
  end

  def contact
    render render_name
  end

  def writeus
    # render render_name
  end

  def handle_message
    if valid_params?(params[:post])
      Rollbar.info("Message sent from web", post: params[:post])

      UserMailer.web_message(params[:post]).deliver
      UserMailer.web_message(params[:post], params[:post][:email]).deliver if params[:post][:copy]

      flash[:notice] = "Success"
      redirect_to :static_writeus
    else
      flash[:notice] = "Invalid input data"
      redirect_to :static_writeus
    end

  end

  def gallery
  end

  def gallery_content
    @album = Album.find(params[:id])
  end

  private
  def render_name
    [params[:controller], 2.times.map{ params[:action] }].flatten.join('/')
  end

  def valid_params? attrs
    return false unless attrs
    return false unless attrs[:email]
    return false unless attrs[:message]
    true
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper

end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_for page
    'active' if page.to_s == params[:action]
  end

end

app/views/albums/_form.html.haml
= form_for @album, html: { class: 'form-horizontal' } do |f|
  - if @album.errors.any?
    #error_explanation
      %h2= "#{pluralize(@album.errors.count, "error")} prohibited this album from being saved:"
      %ul
        - @album.errors.full_messages.each do |msg|
          %li= msg


  .form-group
    .col-sm-offset-2.col-sm-10
      %h4 Pozicija

  .form-group
    = f.label :position, "Position 1-#{Album.count}", class: 'col-sm-2 control-label'
    .col-sm-10
      = f.number_field :position, class: 'form-control'

  %hr
  .form-group
    .col-sm-offset-2.col-sm-10
      %h4 Ime

  - I18n.available_locales.each do |locale|
    .form-group
      = f.label [locale, :name].join('_'), [locale, :ime].join(' ').humanize, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_field [locale, :name].join('_'), class: 'form-control'


  %hr
  .form-group
    .col-sm-offset-2.col-sm-10
      %h4 Slika

  .row
    .col-sm-5.col-sm-offset-2
      .form-group
        = f.label :image, "Slika", class: 'col-sm-2 control-label'
        .col-sm-10
          = f.file_field :image, class: 'direct-upload form-control'
          .helper-text
            = image_tag(@album.image) if @album.image

    .col-sm-5
      .form-group
        = f.label :hover_image, "Aktivna slika", class: 'col-sm-2 control-label'
        .col-sm-10
          = f.file_field :hover_image, class: 'direct-upload form-control'
          .helper-text
            = image_tag(@album.hover_image) if @album.hover_image


  %hr
  .form-group
    = f.label :images, "Slike", class: 'col-sm-2 control-label'
    .col-sm-10
      = f.file_field :images, multiple: true, class: 'direct-upload form-control'
      %br
      %small Klikni na sliko za izbris
      - unless @album.new_record?
        %small
          = link_to "Izbriši vse", album_remove_images_path(@album), :method => :delete, :data => { :confirm => 'Ste prepričani?' }
      .helper-text
        - @album.images.each_with_index do |image, i|
          = link_to album_remove_image_path(@album, i), :method => :delete, :data => { :confirm => 'Ste prepričani?' }, remote: true, id: i do
            = image_tag image, height: 100

  %hr
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit 'Posodobi', class: 'btn btn-primary'
      = link_to 'Nazaj', albums_path, class: 'btn btn-default'

= render 'shared/upload_script', format: :js

app/views/albums/edit.html.haml
%h1.col-sm-10.col-sm-offset-2 Urejanje albuma

= render 'form'

app/views/albums/index.html.haml
%h1 Vsi albumi

%table.table
  %tr
    %th{style: 'width: 30px'} Pozicija
    %th{style: 'width: 150px'} Slika
    %th{style: 'width: 150px'} Aktivna slika
    %th{style: 'width: 400px'} Name
    %th Slike
    %th Akcije

  - @albums.order(:position).each do |album|
    %tr
      %td= album.position
      %td= image_tag(album.image, width: 150)
      %td= image_tag(album.hover_image, width: 150)
      %td= album.name.map{|n| n.join(': ')}.join('<br>').html_safe
      %td.images
        - album.images.each do |image|
          = image_tag image, height: 30
      %td
        = link_to 'Uredi', edit_album_path(album), class: 'btn btn-default'
        = link_to 'Izbriši', album, :method => :delete, :data => { :confirm => 'Ste prepričani?' }, class: 'btn btn-danger'

%center
  = link_to 'Ustvari Album', new_album_path, class: 'btn btn-primary'

app/views/albums/new.html.haml
%h1.col-sm-10.col-sm-offset-2 Nov album

= render 'form'

app/views/albums/remove_image.js.erb
$("#<%=params[:id] %>").fadeOut();

app/views/albums/show.html.haml
%p#notice= notice

%p
  %b Image:
  = image_tag(@album.image_url)
%p
  %b Hover image:
  = image_tag(@album.hover_image_url)
%p
  %b Name:
  = @album.name

= link_to 'Edit', edit_album_path(@album)
\|
= link_to 'Back', albums_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nočitve Angelina - Turistične sobe, Hoteli, Apartmaji, Rogaška Slatina, Slovenija</title>
  <meta name="google-site-verification" content="gD-i8meskUxMuh4rizqQQoIl-Yf1CDSR-5AfXi6fHUc" />
  <link href="/favicon.gif" rel="icon">

  <%= stylesheet_link_tag 'angelina', media: 'all' %>
  <!--[if IE]>
    <%= stylesheet_link_tag 'fancydropdown_ie', media: 'all' %>
  <![endif]-->
  <!--[if !IE]><!-->
    <%= stylesheet_link_tag 'fancydropdown', media: 'all' %>
  <!--<![endif]-->

  <%= csrf_meta_tags %>
</head>
<body>
  <table style="padding-top:20px" align="center" cellpadding="0" cellspacing="0" border="0" width="1003px">
    <tr>
      <td colspan="3" id="t_head">
        <%= link_to root_path, style: 'border:0;' do %>
          <%= image_tag "angelina/design/head.png", style: "border:0; vertical-align:bottom;" %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td id="t_left">&nbsp;&nbsp;&nbsp;</td>
      <td id="t_center">
        <%= render 'shared/menu' %>

        <center>
          <%= link_to t('menu.contact.title'), static_contact_path %>: <a href="tel:0038682051950">+386 (0)82 051 950</a> / <a href="mailto:info@n-angelina.si">info@n-angelina.si</a>
        </center>

        <%= yield %>
      </td>
      <td id="t_right">&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
      <td id="t_left"></td>
      <td id="t_center">
        <%= render 'shared/sponsors' %>
      </td>
      <td id="t_right"></td>
    </tr>
    <tr>
      <td id="b_left"></td>
      <td id="b_center"></td>
      <td id="b_right"></td>
    </tr>
  </table>

  <div id="footer">
    <div style="vertical-align:middle; height:20px">
      <%#= render 'shared/hitcount' %>
    </div>
    <p>&copy; Copyright 2010 Nočitve Angelina. Vse pravice pridržane. &copy;</p>
  </div>

  <%= javascript_include_tag 'angelina' %>
</body>
</html>

app/views/layouts/management.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nočitve Angelina - Management</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= static_gallery_path %>">Angelina</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Albumi</a></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>

  <div class="container">

    <%= yield %>

  </div><!-- /.container -->


</body>
</html>

app/views/shared/_hitcount.html.haml
Število obiskov:
:javascript
  var sc_project = 6697095;
  var sc_invisible = 0;
  var sc_security = "69ef782b";
  var sc_text = 1;
%script{:src => "http://www.statcounter.com/counter/counter.js", :type => "text/javascript"}
%noscript
  .statcounter
    %a{:href => "http://statcounter.com/tumblr/", :target => "_blank", :title => "tumblr stats"}
      %img.statcounter{:alt => "tumblr stats", :src => "http://c.statcounter.com/6697095/0/69ef782b/0/"}/
%br/

app/views/shared/_menu.html.haml
%table{:align => "center", :border => "0", :cellpadding => "0", :cellspacing => "0", :height => "34px"}
  %tr
    %td#menu_first
    %td#menu_item.tabs
      = link_to t('menu.home'), static_home_path, id: 'menu_link', class: active_for(:home)
    %td#menu_item
      = link_to t('menu.pricing'), static_pricing_path, id: 'menu_link', class: active_for(:pricing)
    %td#menu_item
      = link_to t('menu.gallery.title'), static_gallery_path, id: 'menu_link', class: active_for(:gallery)
      .dropdown
        %ul
          %li
            = link_to t('menu.gallery.3d'), 'http://3d.n-angelina.si'
          - Album.all.each do |album|
            %li
              = link_to album.localized_name, static_gallery_content_path(album)
    %td#menu_item
      = link_to t('menu.about.title'), static_about_path, id: 'menu_link', class: active_for(:about)
      .dropdown
        %ul
          %li
            = link_to t('menu.about.position'), static_map_path
          %li
            = link_to t('menu.about.skrabl'), "http://www.skrabl.com"
    %td#menu_item
      = link_to t('menu.activities.title'), static_events_path, id: 'menu_link', class: active_for(:activities)
      .dropdown
        %ul
          %li
            = link_to t('menu.activities.events'), static_events_path
          %li
            = link_to t('menu.activities.culture'), static_culture_path
          %li
            = link_to t('menu.activities.sport'), static_sport_path
    %td#menu_item
      = link_to t('menu.contact.title'), static_contact_path, id: 'menu_link', class: active_for(:contact)
      .dropdown
        %ul
          %li
            = link_to t('menu.contact.writeus'), static_writeus_path
          %li
            = link_to t('menu.contact.card'), static_contact_path
    %td#menu_last

app/views/shared/_sponsors.html.haml
#sponsors
  %span#sponsor
    %a{:href => "http://www.skrabl.com/"}
      = image_tag "sponsors/skrabl_logo.png"
  %span#sponsor
    %a{:href => "http://www.gostiscejurg.si/"}
      = image_tag "sponsors/jurg.png"

app/views/shared/_upload_script.html.haml
:coffeescript
  $ ->
    $(".direct-upload").each (i, elem) ->
      fileInput = $(elem)
      form = $(fileInput.parents("form:first"))
      submitButton = form.find("input[type=\"submit\"]")
      progressBar = $("<div class='bar'></div>")
      barContainer = $("<div class='progress'></div>").append(progressBar)
      fileInput.after barContainer

      fileInput.attr("orig_name", fileInput.attr("name"))
      fileInput.attr("name", "file_upload")

      fileInput.fileupload
        fileInput: fileInput
        url: "#{@album.image_presigned_post.url}"
        type: "POST"
        autoUpload: true
        formData: #{@album.image_presigned_post.fields.to_json.html_safe}
        paramName: "file" # S3 does not like nested name fields i.e. name="user[avatar_url]"
        dataType: "XML" # S3 returns XML if success_action_status is set to 201
        replaceFileInput: false

        progressall: (e, data) ->
          filesCount = parseInt(fileInput.attr('files_count'))
          filesLoaded = (parseInt(fileInput.attr('files_loaded')) || 0)

          progress = parseInt((data.loaded + filesLoaded*(data.total*0.2 / filesCount)) / (data.total*1.2) * 100, 10)
          progressBar.css "width", progress + "%"

        start: (e) ->
          submitButton.prop "disabled", true
          progressBar.css("background", "green").css("display", "block").css("width", "0%").text "Loading..."

          fileInput.attr('files_count', e.target.files.length)

        done: (e, data) ->
          # extract key and generate URL from response
          key = $(data.jqXHR.responseXML).find("Key").text()
          url = "//#{@album.image_presigned_post.url.host}/" + key

          # create hidden field
          input = $("<input />",
            type: "hidden"
            name: fileInput.attr("orig_name")
            value: url
          )
          form.append input

          filesCount = parseInt(fileInput.attr('files_count'))
          filesLoaded = (parseInt(fileInput.attr('files_loaded')) || 0) + 1
          fileInput.attr('files_loaded', filesLoaded)

          if filesLoaded == filesCount
            submitButton.prop "disabled", false
            progressBar.text "Uploading done"
            progressBar.css "width", "100%"

        fail: (e, data) ->
          submitButton.prop "disabled", false
          progressBar.css("background", "red").text "Failed"